### ISSUE TITLE
Konzeptionierung Datenbank

### ISSUE THREAD

**Issue by ChrisKegel2901** [Bjoern93/Fallstudie-WWI13AMC-Twitter#3]
Nach einiger Überlegung hat sich die Verwendung einer Datenbank zur Speicherung der Werte als vorteilhaft präsentiert. Allerdings stellt uns das Konzept für die Speicherung der Locations vor einige Probleme.

Frage an Björn: Sollen nur einige Länder/Sprachen verwendet werden oder alle?

Konzept:
![db](https://cloud.githubusercontent.com/assets/12609702/7867584/3fd1068a-0577-11e5-98b3-78ccdee8038b.png)
Neue Länder werden dann über ALTER TABLE als Spalte eingefügt. Counter errechnet sich aus Summe der Zahlen die in einer Spalte stehen.

**Comment by Bjoern93** [comment]
Kannst du einschätzen wie hoch der Aufwand wäre eine Funktion zu
implementieren welche prüft ob ein Standort / Sprache  in der DB hinterlegt
und diesen, sofern nicht vorhanden, anlegt?
Wie wären die Auswirkungen auf die Laufzeit?
Am 28.05.2015 19:38 schrieb "ChrisKegel2901" <notifications@github.com>:

**Comment by ChrisKegel2901** [comment]
Das wäre eine Option, klar könnte man machen. War mir nur nicht sicher wie das gedacht war. Dann mach ich mich mal an ein Konzept.

**Comment by ChrisKegel2901** [comment]
Nochmal generell der Hintergrund:

Ich habe eben testweise mal diese Twitter Implementierung geschrieben um zu verstehen wie das funktioniert um den Aufwand abschätzen zu können.
Dabei ist mir aufgefallen, dass die Anzahl an Nachrichten, die da reinkommt nicht gerade super hoch ist,
ich hab ca. 30 Minuten gewartet und #LH oder #Lufthansa kamen ZUSAMMEN nur 9 mal.

Deshalb lag es in meinen Augen nahe, die Daten in der DB zu loggen, also z.B. LH = 9, auf die dann beim nächsten Start der Anwendung zurückgegriffen werden kann. Das sie eben nicht anfängt, die Tweets von Neuem zu zählen, sondern bei dem "Letzten Stand" anfängt.
Deshalb hab ich Björn gefragt wie das gedacht war.

**Comment by Bjoern93** [comment]
Wie kommuniziert wird eine DB eingerichtet. 
Kannst du dich hier an die Konzeption des Schemas setzen? 

Danke!

**Comment by ChrisKegel2901** [comment]
Bin schon dabei.

**Comment by ChrisKegel2901** [comment]
Konzeptionierung abgeschlossen. Nachfolge-Issue "Datenbank Implementierung" wird erstellt.

Issue closed.
